### ISSUE TITLE
Helm Resources Limits/Request CPU and Memory

### ISSUE THREAD

**Issue by iperezx** [mintproject/mint#36]
Can there be support to configure the resources limits/requests for CPU and memory so that it can be configured in the `values.yaml` file?

Our k8s cluster blocks any objects that don't have the resources set in the manifest files.

**Comment by mosoriob** [comment]
Hey @iperezx,

Thank you for bringing this to my attention. It's definitely a good idea to add resource limits/requests for CPU and memory. My schedule is quite tight at the moment, but I can add it next week. If you would like to implement it yourself, I'm happy with that too.
